# Generated by Django 4.0.8 on 2022-12-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='FirstName',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='LastName',
            new_name='designation',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='Designation',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.AddField(
            model_name='employee',
            name='_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
